import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
} from "@solana/spl-token";

// Load IDL (generated by `anchor build`)
import idl from "../target/idl/norse_token.json";

const PROGRAM_ID = new PublicKey("NRSEtokenXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

async function main() {
  // Configure the client
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = new Program(idl as any, PROGRAM_ID, provider);
  const deployer = provider.wallet;

  console.log("=".repeat(60));
  console.log("  NorseCoin Solana Deployment Script");
  console.log("=".repeat(60));
  console.log(`Deployer: ${deployer.publicKey.toBase58()}`);
  console.log(`Cluster:  ${provider.connection.rpcEndpoint}`);
  console.log();

  // ────────────────────────────────────────────────
  //  Step 1: Initialize Token Mint
  // ────────────────────────────────────────────────
  console.log("Step 1: Initializing NORSE token mint...");

  const tokenMint = Keypair.generate();
  const [mintAuthority] = PublicKey.findProgramAddressSync(
    [Buffer.from("mint-authority")],
    program.programId
  );
  const deployerTokenAccount = await getAssociatedTokenAddress(
    tokenMint.publicKey,
    deployer.publicKey
  );

  try {
    await program.methods
      .initializeToken()
      .accounts({
        deployer: deployer.publicKey,
        tokenMint: tokenMint.publicKey,
        mintAuthority,
        deployerTokenAccount,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([tokenMint])
      .rpc();

    console.log(`  Token Mint:    ${tokenMint.publicKey.toBase58()}`);
    console.log(`  Deployer ATA:  ${deployerTokenAccount.toBase58()}`);
    console.log("  1 trillion NORSE tokens minted to deployer");
  } catch (err) {
    console.error("  Failed to initialize token:", err);
    return;
  }

  // ────────────────────────────────────────────────
  //  Step 2: Initialize Staking Pool
  // ────────────────────────────────────────────────
  console.log("\nStep 2: Initializing staking pool with Nine Realms...");

  const [stakingPool] = PublicKey.findProgramAddressSync(
    [Buffer.from("staking-pool")],
    program.programId
  );
  const [stakingVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("staking-vault")],
    program.programId
  );

  try {
    await program.methods
      .initializeStaking()
      .accounts({
        authority: deployer.publicKey,
        tokenMint: tokenMint.publicKey,
        stakingPool,
        stakingVault,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .rpc();

    console.log(`  Staking Pool:  ${stakingPool.toBase58()}`);
    console.log(`  Staking Vault: ${stakingVault.toBase58()}`);
    console.log("  Nine Realms configured (Midgard through Muspelheim)");
  } catch (err) {
    console.error("  Failed to initialize staking:", err);
    return;
  }

  // ────────────────────────────────────────────────
  //  Step 3: Fund Reward Pool
  // ────────────────────────────────────────────────
  console.log("\nStep 3: Funding staking reward pool...");

  // Allocate 10% of supply (100B tokens) for staking rewards
  const rewardAmount = new anchor.BN(100_000_000_000).mul(
    new anchor.BN(1_000_000_000)
  );

  try {
    await program.methods
      .fundRewardPool(rewardAmount)
      .accounts({
        funder: deployer.publicKey,
        stakingPool,
        stakingVault,
        funderTokenAccount: deployerTokenAccount,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    console.log(`  Funded with 100 billion NORSE tokens for rewards`);
  } catch (err) {
    console.error("  Failed to fund reward pool:", err);
    return;
  }

  // ────────────────────────────────────────────────
  //  Step 4: Initialize Presale
  // ────────────────────────────────────────────────
  console.log("\nStep 4: Initializing presale with 3 stages...");

  const [presaleState] = PublicKey.findProgramAddressSync(
    [Buffer.from("presale-state")],
    program.programId
  );
  const [presaleTokenVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("presale-token-vault")],
    program.programId
  );

  try {
    await program.methods
      .initializePresale()
      .accounts({
        authority: deployer.publicKey,
        tokenMint: tokenMint.publicKey,
        presaleState,
        presaleTokenVault,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .rpc();

    console.log(`  Presale State: ${presaleState.toBase58()}`);
    console.log(`  Token Vault:   ${presaleTokenVault.toBase58()}`);
    console.log("  Stages: Ragnarok / Valhalla / Odin's Blessing");
  } catch (err) {
    console.error("  Failed to initialize presale:", err);
    return;
  }

  // ────────────────────────────────────────────────
  //  Step 5: Transfer Presale Allocation
  // ────────────────────────────────────────────────
  console.log("\nStep 5: Transferring presale allocation...");

  // Allocate 30% of supply (300B tokens) for presale (100B per stage)
  const presaleAmount = new anchor.BN(300_000_000_000).mul(
    new anchor.BN(1_000_000_000)
  );

  try {
    // Direct SPL token transfer from deployer to presale vault
    const transferIx = anchor.web3.SystemProgram.programId; // placeholder
    await program.provider.sendAndConfirm!(
      new anchor.web3.Transaction().add(
        // Use SPL Token transfer instruction
        {
          keys: [
            { pubkey: deployerTokenAccount, isSigner: false, isWritable: true },
            { pubkey: presaleTokenVault, isSigner: false, isWritable: true },
            { pubkey: deployer.publicKey, isSigner: true, isWritable: false },
          ],
          programId: TOKEN_PROGRAM_ID,
          data: Buffer.from([3, ...new anchor.BN(presaleAmount).toArray("le", 8)]),
        }
      )
    );

    console.log(`  Transferred 300 billion NORSE tokens to presale vault`);
  } catch (err) {
    console.error("  Failed to transfer presale allocation:", err);
    console.log("  You can manually transfer using:");
    console.log(`    spl-token transfer ${tokenMint.publicKey.toBase58()} 300000000000000000000 ${presaleTokenVault.toBase58()}`);
  }

  // ────────────────────────────────────────────────
  //  Step 6: Initialize NFT Collection
  // ────────────────────────────────────────────────
  console.log("\nStep 6: Initializing NFT collection...");

  const [nftCollection] = PublicKey.findProgramAddressSync(
    [Buffer.from("nft-collection")],
    program.programId
  );

  try {
    await program.methods
      .initializeNftCollection()
      .accounts({
        authority: deployer.publicKey,
        nftCollection,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log(`  NFT Collection: ${nftCollection.toBase58()}`);
    console.log("  Norse Viking Artifacts - 10,000 supply, 0.5 SOL each");
  } catch (err) {
    console.error("  Failed to initialize NFT collection:", err);
  }

  // ────────────────────────────────────────────────
  //  Summary
  // ────────────────────────────────────────────────
  console.log("\n" + "=".repeat(60));
  console.log("  Deployment Summary");
  console.log("=".repeat(60));
  console.log(`Program ID:       ${PROGRAM_ID.toBase58()}`);
  console.log(`Token Mint:       ${tokenMint.publicKey.toBase58()}`);
  console.log(`Staking Pool:     ${stakingPool.toBase58()}`);
  console.log(`Staking Vault:    ${stakingVault.toBase58()}`);
  console.log(`Presale State:    ${presaleState.toBase58()}`);
  console.log(`Presale Vault:    ${presaleTokenVault.toBase58()}`);
  console.log(`NFT Collection:   ${nftCollection.toBase58()}`);
  console.log();
  console.log("Next steps:");
  console.log("  1. Activate presale stage: set_stage_active(0, true)");
  console.log("  2. Enable NFT minting: toggle_nft_minting()");
  console.log("  3. Set TGE time when ready: set_tge_time(timestamp)");
  console.log("=".repeat(60));
}

main().catch(console.error);
